### ISSUE TITLE
[Data] Remove duplicate, null geometries

### ISSUE THREAD

**Issue by danielduhh** [spatialdev/react-chbp#17]
There are a bunch of duplicate features with null geometries that we need to delete.

<img width="959" alt="Screen Shot 2019-07-15 at 4 09 12 PM" src="https://user-images.githubusercontent.com/1947857/61254860-07e64d80-a71b-11e9-8dad-e5b4066d53e5.png">

**Comment by shawat94** [comment]
Many of the null geometries are for businesses that are pending clearance to be added, so at least one will need to be retained. Other than that, there are several duplicate geometries that are leftovers from a join to gather the descriptions.

**Comment by danielduhh** [comment]
Yeah... I think the biggest issue that that they points of interest (Point Features) and the generated label centroid labels have the same feature ids, for example ->
Wildrose has two features with the same id
```json
    {
      "type": "Feature",
      "properties": {
        "id": 62,
        "name": "Wildrose",
        "type": "Restaurant \/ Bar",
        "description": "Wildrose is one of the oldest lesbian bars on the West Coast, offering DJs, karaoke & seasonal outdoor seating.",
        "website": "wildrosebar.com"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.318393907775118,
          47.613983787026143
        ]
      }
    }
```
And
```json
{
      "type": "Feature",
      "properties": {
        "id": 62,
        "name": "Wildrose",
        "type": "Restaurant \/ Bar",
        "description": "Wildrose is one of the oldest lesbian bars on the West Coast, offering DJs, karaoke & seasonal outdoor seating.",
        "website": "wildrosebar.com",
        "show_label": "",
        "show_icon": "",
        "icon": "",
        "rotate": "",
        "left_panel": ""
      },
      "geometry": {
        "type": "MultiPolygon",
        ...
```
