### ISSUE TITLE
Digitize paper maps

### ISSUE THREAD

**Issue by danielduhh** [spatialdev/react-chbp#2]
Using the paper map and spreadsheet attached, create a digitized geojson that has all of the relevant elements.

I'm working with Kate Harris (kate@capitolhillblockparty.com) to coordinate prioritizing the block party data.

[Interactive Map Master.xlsx](https://github.com/spatialdev/react-chbp/files/3357032/Interactive.Map.Master.xlsx)
[CHBP 2019 Site Map 6.11.19.pdf](https://github.com/spatialdev/react-chbp/files/3357033/CHBP.2019.Site.Map.6.11.19.pdf)

**Comment by shawat94** [comment]
Much of the current polygon geometry will be converted to point centroid geometry based on priority (significant objects such as stages will still be represented as polygons).

**Comment by shawat94** [comment]
To do:

- Filter out polygon and centroid layers to restrict polygon geometry only to significant objects (stages, beer garden, etc)
- Finish updating description field (currently set to 'description3' to allow for a larger string length tolerance; will be renamed once the original description field is no longer needed and is removed)
- Add display characteristics based on symbology using field calculator/manual changes
- Replace any missing information from spreadsheet on each object

**Comment by danielduhh** [comment]
This is done! Thanks @shawat94 and @stephencerqueira
