### ISSUE TITLE
"Now Playing" Ticker

### ISSUE THREAD

**Issue by slindy23** [spatialdev/react-chbp#24]
Add a feature to the top banner that lists what is currently playing on each stage... 

Would continuously go and update as the schedule changes. 

<img width="804" alt="Screen Shot 2019-07-16 at 8 00 21 AM" src="https://user-images.githubusercontent.com/3790458/61305523-cf3c8780-a79f-11e9-94e2-41e36ba72f2a.png">

**Comment by danielduhh** [comment]
Fixed by #33 !
