### ISSUE TITLE
[Data] Remove all TBD features from json

### ISSUE THREAD

**Issue by danielduhh** [spatialdev/react-chbp#30]
There's a bunch of `TBD` named features in the json that need to be removed. For example,
```
    {
      "type": "Feature",
      "properties": {
        "id": 146,
        "name": "TBD",
        "type": null,
        "description": null,
        "website": null
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.31941927661441,
          47.61496722003707
        ]
      }
    }
```

**Comment by shawat94** [comment]
<img width="660" alt="Screen Shot 2019-07-17 at 11 37 49 PM" src="https://user-images.githubusercontent.com/33205894/61435771-23ee1880-a8ee-11e9-83fb-fe8b27bdcf86.png">
<img width="1232" alt="Screen Shot 2019-07-17 at 11 38 04 PM" src="https://user-images.githubusercontent.com/33205894/61435772-23ee1880-a8ee-11e9-8733-34a66c4602d7.png">
<img width="351" alt="Screen Shot 2019-07-17 at 11 38 43 PM" src="https://user-images.githubusercontent.com/33205894/61435773-2486af00-a8ee-11e9-852a-4e05a9dd1c26.png">
